config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'movies/new_from_lookup' => 'movies#new_from_lookup', as: :new_movie_from_lookup
  get 'movies/search_by_title' => 'movies#search_by_title'
  get 'movies/admin' => 'movies#admin', as: :movie_admin
  get 'movies/:id/status' => 'movies#status', as: :movie_status
  get 'movies/:id/manage' => 'movies#manage', as: :manage_movie
  get 'movies/:id/build' => 'movies#build', as: :build_movie
  get '/movies', to: redirect('/')
  resources :movies

  get 'stats/refresh' => 'statistics#refresh', as: :stats_refresh
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD'], except: [:index, :show, :search_by_title, :compare]

  def admin
    @movies = Movie.order('created_at DESC')
  end

  def show
    @movie = Movie.find_by_slug(params[:id])

    if @movie.stats.empty?
      flash[:alert] = "This movie's information is not yet complete. Please try again later"
      redirect_to :root
    else
      respond_to do |format|
        format.html
        format.json  { render json: @movie, except: [:id, :page_depth, :rotten_tomatoes_id, :status, :created_at, :updated_at, :task, :complete, :slug]}
        format.xml  { render xml: @movie, except: [:id, :page_depth, :rotten_tomatoes_id, :status, :created_at, :updated_at, :task, :complete, :slug]}
      end
    end
  end

  def manage
    @movie = Movie.find_by_slug(params[:id])

    @cast_count = 3
    @cast_count = 1000 if params[:all_cast]

    @review_count = 5
    @review_count = 10000 if params[:all_reviews]
  end

  def search_by_title
    if params[:query].blank?
      flash[:alert] = "No search term provided."
      return redirect_to :root
    else
      @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html {
        PotentialMovie.delay.log(params[:query])
        return redirect_to movie_path(@movies.first) if @movies.length == 1
      }
      format.json { render :json => @movies.to_json }
    end
  end

  def new
    @movie = Movie.new(page_depth: 1)
  end

  def new_from_lookup
    bf = BadFruit.new(ENV['BADFRUIT_KEY'])
    @movies = []
    @movies = bf.movies.search_by_name(params[:query], 3) if params[:query]
    @movies.each do |movie|
      movie.genres = bf.movies.search_by_id(movie.id).genres
    end
  end

  def edit
    @movie = Movie.find_by_slug(params[:id])
  end

  def create
    params = movie_params
    params[:genres] = params[:genres].split(', ')
    if Movie.exists?(title: params[:title])
      flash[:alert] = "This movie already exists."
      redirect_to new_movie_from_lookup_path
    else
      @movie = Movie.create(params)
      redirect_to manage_movie_path(@movie)
    end
  end

  def update
    @movie = Movie.find_by_slug(params[:id])
    params = movie_params
    params[:genres] = params[:genres].split(', ')
    @movie.update_attributes(params)
    redirect_to manage_movie_path(@movie)
  end

  def destroy
    Movie.find_by_slug(params[:id]).destroy
    redirect_to movie_admin_path
  end

  def status
    @movie = Movie.find_by_slug(params[:id])
    render layout: false
  end

  def build
    @movie = Movie.find_by_slug(params[:id])
    @movie.update_attribute(:status, '0%')
    @movie.build
    redirect_to manage_movie_path(@movie)
  end

  private
    def movie_params
      params.require(:movie).permit(
        :title,
        :page_depth,
        :imdb_link,
        :amazon_link,
        :metacritic_link,
        :rotten_tomatoes_link,
        :rotten_tomatoes_id,
        :image_url,
        :year,
        :genres
      )
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def comparison_summary(movie_1, movie_2)
    winners = {overall_sentiment: :both, review_controversy: :both}

    movie_1.sentiment[:topics].each do |topic|
      if movie_2.sentiment[:topics][topic[0]] && topic[1] > movie_2.sentiment[:topics][topic[0]]
        winners[:overall_sentiment] = movie_1.title
      elsif movie_2.sentiment[:topics][topic[0]] && topic[1] < movie_2.sentiment[:topics][topic[0]]
        winners[:overall_sentiment] = movie_2.title
      end
    end

    if movie_2.sentiment[:distribution_stats][:st_dev] > movie_1.sentiment[:distribution_stats][:st_dev]
      winners[:review_controversy] = movie_2.title
    elsif movie_2.sentiment[:distribution_stats][:st_dev] < movie_1.sentiment[:distribution_stats][:st_dev]
      winners[:review_controversy] = movie_1.title
    end

    winners
  end
end

app/views/movies/_form.html.slim
= form_for @movie do |f|
  div
    label Title&nbsp;
    = f.text_field :title, placeholder: 'Title', value: params[:title] || @movie.title

  fieldset
    legend Source Links
    p.comment These can be populated automatically once the movie is created.
    label IMDb Link&nbsp;
    = f.text_field :imdb_link, placeholder: '(optional)', value: @movie.imdb_link
    label Amazon Link&nbsp;
    = f.text_field :amazon_link, placeholder: '(optional)', value: @movie.amazon_link
    label Metacritic Link&nbsp;
    = f.text_field :metacritic_link, placeholder: '(optional)', value: @movie.metacritic_link
    label Rotten Tomatoes Link&nbsp;
    = f.text_field :rotten_tomatoes_link, placeholder: '(optional)', value: params[:rotten_tomatoes_link] || @movie.rotten_tomatoes_link

  fieldset
    legend Other
    label Rotten Tomatoes ID&nbsp;
    p.comment Used for metadata collection (cast, image, year)
    = f.text_field :rotten_tomatoes_id, placeholder: 'Rotten Tomatoes ID', value: params[:rotten_tomatoes_id] || @movie.rotten_tomatoes_id
    label Poster/Art URL&nbsp;
    = f.text_field :image_url, placeholder: 'Image URL', value: params[:image_url] || @movie.image_url
    label Year&nbsp;
    = f.text_field :year, placeholder: 'Year', value: params[:year] || @movie.year
    label Genres&nbsp;
    -genres = params[:genres] || @movie.genres
    = f.text_field :genres, placeholder: 'Genres', value: genres.join(', ')
    label Page Scan Depth&nbsp;
    p.comment The number of review pages per source that will be scanned - the larger the number the longer it takes
    = f.number_field(:page_depth, in: 1..10, step: 1)
  br
  = f.submit 'Save', id: 'new_film_submit'

app/views/movies/admin.html.slim
h1 Manage Movies
=link_to 'New', new_movie_from_lookup_path
=link_to 'Refresh Average Stats', stats_refresh_path, id: 'refresh_stats_btn'
table
  tr
    th Image
    th Title
    th Created
    th colspan=(2)
      | Actions
  -@movies.each do |m|
    tr
      td =image_tag(m.image_url)
      td =m.title
      td =distance_of_time_in_words(Time.new, m.created_at) + ' ago'
      td =link_to 'Manage', manage_movie_path(m)
      td =button_to "Delete", m, {onclick: "return confirm('Sure?')", method: :delete}

app/views/movies/edit.html.slim
h1 =@movie.title
=render 'form', locals: {movie: @movie}
=button_to "Delete", @movie, {onclick: "return confirm('Sure?')", method: :delete}

app/views/movies/manage.html.slim
javascript:
  $(document).ready(function(){
      $(".async").click(function(){
        $(this).html("Loading...");
        $(this).css("background-color", "green");
      });
  });

=link_to "Back", movie_admin_path
h1 =@movie.title
=render 'movies/show/actions', movie: @movie
=render 'movies/show/build_summary', movie: @movie

app/views/movies/new.html.slim
h2 New Film
=render 'form', locals: {movie: @movie}

app/views/movies/new_from_lookup.html.slim
=form_tag new_movie_from_lookup_path, :method => 'get', id: "new_from_lookup_form" do
  = text_field_tag :query, params[:query], placeholder: 'Film Title'
  = submit_tag "Search", name: nil, id: 'new_from_lookup_btn'

-unless @movies.empty?
  table
    tr
      th id
      th poster
      th title
      th year
      th genres
      th cast
      th link
      th create
    -@movies.each do |movie|
      tr
        td
          strong =movie.id
        td =image_tag(movie.posters.thumbnail)
        td =movie.name
        td =movie.year
        td =movie.genres.first
        td
          ul
            -movie.cast.each do |member|
              li =member['name']
        td =link_to 'View', movie.links['alternate']
        td =link_to 'Use as Template', new_movie_path(title: movie.name, image_url: movie.posters.thumbnail, year: movie.year, rotten_tomatoes_id: movie.id, rotten_tomatoes_link: movie.links['alternate'], genres: movie.genres)

app/views/movies/search_by_title.html.slim
-if !@movies.empty?
  h3="Results for '#{params[:query]}'"
  table
    -@movies.each do |movie|
      tr
        td =link_to movie.title, movie_path(movie)
        td =image_tag(movie.image_url)
-else
  h3="No results found for '#{params[:query]}'"

app/views/movies/show.html.slim
h1 =@movie.title
.row
  .column-5
    .cover
      =image_tag(@movie.image_url)
    table
      tr
        th Year
        td =@movie.year
      tr
        th Genres
        td =@movie.genres.join('<br/>').html_safe
      -unless @movie.related_people[:directors].nil?
        tr
          th Directors
          td
            -@movie.related_people[:directors] \
              .map { |d| d['name'] }.each do |director|
                =director
                br
      tr
        th Starring
        td
          -@movie.related_people[:cast].to_a.take(3) \
            .map { |member| member[:name] }.each do |star|
              =star
              br
    strong Added
    br
    =@movie.created_at.strftime("%e %B %Y")
    =" (Updated " + distance_of_time_in_words(Time.new, @movie.updated_at).gsub('about ', '') + " ago)"
    br
    strong References
    br
    -@movie.references.each do |reference|
      =link_to reference.gsub('http://www.', ''), reference
      br
    br

  .column-7
    h3 Aspect Sentiment vs Discussion Focus
    =render "application/aspects_graph", id: @movie.id, aspects: @movie.sentiment[:topics], counts: @movie.stats[:topic_counts]
    -unless @movie.sentiment[:people].empty?
      h3 Cast Sentiment
      =render "application/cast_sentiment_graph", id: @movie.id, people: @movie.sentiment[:people]

app/views/movies/status.html.slim
.progress
  span.meter id=("#{@movie.id}") style=("width: #{@movie.status}")