config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'movies/new_from_lookup' => 'movies#new_from_lookup', as: :new_movie_from_lookup
  get 'movies/search_by_title' => 'movies#search_by_title'
  get 'movies/admin' => 'movies#admin', as: :movie_admin
  get 'movies/:id/status' => 'movies#status', as: :movie_status
  get 'movies/:id/manage' => 'movies#manage', as: :manage_movie
  get 'movies/:id/build' => 'movies#build', as: :build_movie
  get '/movies', to: redirect('/')
  resources :movies

  get 'stats/refresh' => 'statistics#refresh', as: :stats_refresh
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :method_name

  def index
    @movie_count = Movie.complete.size
    @review_count = Statistic.get_stat('review_count').value[:count]
    @aspects = Statistic.get_stat('topic_sentiments').value
    @counts = Statistic.get_stat('topic_counts').value
    @movies = Movie.complete.order('created_at DESC').limit(10).select(['id', 'title', 'slug', 'created_at'])
    @movies_list = Movie.complete.select('title').to_a.map {|m| m.title}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_aspects_graph.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    var options = {
      scaleBeginAtZero : false,
      scaleShowGridLines : true,
      scaleGridLineColor : "rgba(0,0,0,.05)",
      scaleGridLineWidth : 0.5,
      scaleShowHorizontalLines: true,
      scaleShowVerticalLines: true,
      showTooltips: false,
      pointLabelFontSize : 11,
      pointDot: true,
      pointDotRadius: 2,
      datasetStrokeWidth : 1
    };

    var data = {
      labels: <%= aspects.keys.map { |k| k.to_s.capitalize }.to_s.html_safe %>,
      datasets: [
        {
          fillColor: "rgba(220,100,100,0.2)",
          strokeColor: "rgba(0,0,0,0)",
          data: <%= ([0] * aspects.size).to_s %>,
          pointColor : "rgba(220,220,220,0)",
        },
        {
          fillColor: "rgba(150,220,100,0.8)",
          strokeColor: "rgba(140,200,90,0)",
          pointColor : "rgba(140,200,90,0)",
          data: <%= aspects.values %>
        },
        {
          fillColor: "rgba(255,157,0,0.0)",
          strokeColor: "rgba(255,119,0,1)",
          pointColor : "rgba(255,119,0,1)",
          data: <%= counts.values %>
        }
      ]
    }

    var ctx_topics = $("#<%= id %>_aspects").get(0).getContext("2d");
    var topicsChart = new Chart(ctx_topics).Radar(data, options);
  })
</script>

<canvas id="<%= id %>_aspects" width="500" height="300"></canvas>

<p class="graph-comment"><span style="background-color: rgba(140,200,90,1); border-radius: 3px; padding: 3px; color: rgba(255,255,255,0.9); font-size: 12px;">Sentiment</span>  how positive or negative the discussion was.
<br/>
<span style="background-color: rgba(255,119,0,1); border-radius: 3px; padding: 3px; color: rgba(255,255,255,0.9); font-size: 12px;">Focus</span> what most people talk about.</p>

app/views/application/_cast_sentiment_graph.html.erb
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = new google.visualization.DataTable();

    data.addColumn('number', 'Sentiment');
    data.addColumn('number', 'Mentions');
    data.addColumn({
        type: 'string',
        role: 'tooltip'
    });
    data.addColumn({
        type: 'string',
        role: 'style'
    });

    data.addRows(
      <%= people.map { |p| p.reverse << 'point { size: 6; shape-type: star; shape-dent: 0.6; fill-color: #99DB6B; stroke-color: #8FC861; stroke-width: 1.5' }.to_s.html_safe %>
    );

    var options = {
      chartArea: {'width': '85%', 'height': '80%'},
      backgroundColor: "transparent",
      fontSize: 13,
      colors: ['rgb(153,219,107)'],
      tooltip: {isHtml: true},
      hAxis: {
        title: 'Mentions',
        titleTextStyle: {color: 'rgb(110, 124, 128)', italic: false},
        textPosition: 'none',
        gridlines: {color: 'rgb(231, 231, 231)'},
        baselineColor: 'rgb(200, 200, 200)',
        minValue: <%= people.map { |p| p[2] }.min %>,
        maxValue: <%= people.map { |p| p[2] }.max %>
      },
      vAxis: {
        title: 'Sentiment',
        titleTextStyle: {color: 'rgb(110, 124, 128)', italic: false},
        textPosition: 'none',
        gridlines: {color: 'rgb(231, 231, 231)'},
        baselineColor: 'rgb(200, 200, 200)',
        minValue: <%= people.map { |p| p[1] }.min %>,
        maxValue: <%= people.map { |p| p[1] }.max %>
      },
      legend: 'none'
    };

    var chart = new google.visualization.ScatterChart(document.getElementById('<%= id %>_cast_sentiment'));

    chart.draw(data, options);
  }
</script>

<div id="<%= id %>_cast_sentiment" width="500" height="250"></div>
<p>Hover to see cast member names</p>

app/views/application/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59420455-1', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/application/_navbar.html.slim
.navbar
  .row
    .column-12
      =link_to :root do
        =image_tag('/logo.jpg', width: '170px')
      form action='/movies/search_by_title'
        input id='movie-search-box' type='text' name='query' placeholder='Search movies'
        input type='submit' value='Search'

app/views/application/_topics_graph.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    var options = {
      scaleBeginAtZero : false,
      scaleShowGridLines : true,
      scaleGridLineColor : "rgba(0,0,0,.05)",
      scaleGridLineWidth : 1,
      scaleShowHorizontalLines: true,
      scaleShowVerticalLines: true,
      barShowStroke : true,
      barStrokeWidth : 2,
      barValueSpacing : 5,
      barDatasetSpacing : 1,
      legendTemplate : "",
      showTooltips: false,
      pointLabelFontSize : 13,
      pointDot : false,
    };

    var data = {
      labels: <%= topics.map { |x| x[0].to_s.capitalize + ": #{x[1].round(2)}" }.to_s.html_safe %>,
      datasets: [
        {
          fillColor: "rgba(220,100,100,0.2)",
          strokeColor: "rgba(220,100,100,0.2)",
          data: <%= ([0] * topics.size).to_s %>
        },
        {
          fillColor: "rgba(150,220,100,1)",
          strokeColor: "rgba(140,200,90,1)",
          data: <%= topics.map { |x| (x[1] * 100).floor } %>
        }
      ]
    }

    var ctx_topics = $("#<%= id %>_topics").get(0).getContext("2d");
    var topicsChart = new Chart(ctx_topics).Radar(data, options);
  })
</script>

<canvas id="<%= id %>_topics" style="max-width: 550px; max-height: 300px"></canvas>

app/views/application/disclaimer.html.slim
.row
  .large-12.columns
    h1="Disclaimer"
    p.slogan How we get our data, and how we calculate our stats.

.row
  .large-6.columns
    .panel
      h3 Data
      p Our movie and review data comes from publically-avaialble information on IMDB and Rotten Tomatoes. 
      p All review data shown by our site is anonymous.
  .large-6.columns
    .panel
      h3 Stats calculation
      p While our site aims to be as accurate as possible in it's analysis of reviews, there is always a chance that it will get something wrong. Rescore in no way guarantees the accuracy of movie data.

.row
  .large-12.columns
    .panel
      h3 Details
      p Our system works by gathering reviews from sites like IMDB and Rotten Tomatoes, and then scanning their content to produce statistics like sentiment etc.

app/views/application/index.html.slim
-if @movies
  .row
    .column-12 id='search-results'
  .row
    .column-7
      h3 Average Movie Sentiment
      =render "aspects_graph", id: 'stats', aspects: @aspects, counts: @counts
    .column-5
      h3 ="#{Movie.count} movies, #{@review_count} reviews revisited"
      strong Recently Added
      br
      -@movies.each do |movie|
        =link_to(movie.title, movie_path(movie))
        span
          |&nbsp;added&nbsp;
          =distance_of_time_in_words(Time.zone.now, movie.created_at) + ' ago'
        br