config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'movies/new_from_lookup' => 'movies#new_from_lookup', as: :new_movie_from_lookup
  get 'movies/search_by_title' => 'movies#search_by_title'
  get 'movies/admin' => 'movies#admin', as: :movie_admin
  get 'movies/:id/status' => 'movies#status', as: :movie_status
  get 'movies/:id/manage' => 'movies#manage', as: :manage_movie
  get 'movies/:id/build' => 'movies#build', as: :build_movie
  get '/movies', to: redirect('/')
  resources :movies

  get 'stats/refresh' => 'statistics#refresh', as: :stats_refresh
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD'], except: [:index, :show, :search_by_title, :compare]

  def admin
    @movies = Movie.order('created_at DESC')
  end

  def show
    @movie = Movie.find_by_slug(params[:id])

    if @movie.stats.empty?
      flash[:alert] = "This movie's information is not yet complete. Please try again later"
      redirect_to :root
    else
      respond_to do |format|
        format.html
        format.json  { render json: @movie, except: [:id, :page_depth, :rotten_tomatoes_id, :status, :created_at, :updated_at, :task, :complete, :slug]}
        format.xml  { render xml: @movie, except: [:id, :page_depth, :rotten_tomatoes_id, :status, :created_at, :updated_at, :task, :complete, :slug]}
      end
    end
  end

  def manage
    @movie = Movie.find_by_slug(params[:id])

    @cast_count = 3
    @cast_count = 1000 if params[:all_cast]

    @review_count = 5
    @review_count = 10000 if params[:all_reviews]
  end

  def search_by_title
    if params[:query].blank?
      flash[:alert] = "No search term provided."
      return redirect_to :root
    else
      @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html {
        PotentialMovie.delay.log(params[:query])
        return redirect_to movie_path(@movies.first) if @movies.length == 1
      }
      format.json { render :json => @movies.to_json }
    end
  end

  def new
    @movie = Movie.new(page_depth: 1)
  end

  def new_from_lookup
    bf = BadFruit.new(ENV['BADFRUIT_KEY'])
    @movies = []
    @movies = bf.movies.search_by_name(params[:query], 3) if params[:query]
    @movies.each do |movie|
      movie.genres = bf.movies.search_by_id(movie.id).genres
    end
  end

  def edit
    @movie = Movie.find_by_slug(params[:id])
  end

  def create
    params = movie_params
    params[:genres] = params[:genres].split(', ')
    if Movie.exists?(title: params[:title])
      flash[:alert] = "This movie already exists."
      redirect_to new_movie_from_lookup_path
    else
      @movie = Movie.create(params)
      redirect_to manage_movie_path(@movie)
    end
  end

  def update
    @movie = Movie.find_by_slug(params[:id])
    params = movie_params
    params[:genres] = params[:genres].split(', ')
    @movie.update_attributes(params)
    redirect_to manage_movie_path(@movie)
  end

  def destroy
    Movie.find_by_slug(params[:id]).destroy
    redirect_to movie_admin_path
  end

  def status
    @movie = Movie.find_by_slug(params[:id])
    render layout: false
  end

  def build
    @movie = Movie.find_by_slug(params[:id])
    @movie.update_attribute(:status, '0%')
    @movie.build
    redirect_to manage_movie_path(@movie)
  end

  private
    def movie_params
      params.require(:movie).permit(
        :title,
        :page_depth,
        :imdb_link,
        :amazon_link,
        :metacritic_link,
        :rotten_tomatoes_link,
        :rotten_tomatoes_id,
        :image_url,
        :year,
        :genres
      )
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def comparison_summary(movie_1, movie_2)
    winners = {overall_sentiment: :both, review_controversy: :both}

    movie_1.sentiment[:topics].each do |topic|
      if movie_2.sentiment[:topics][topic[0]] && topic[1] > movie_2.sentiment[:topics][topic[0]]
        winners[:overall_sentiment] = movie_1.title
      elsif movie_2.sentiment[:topics][topic[0]] && topic[1] < movie_2.sentiment[:topics][topic[0]]
        winners[:overall_sentiment] = movie_2.title
      end
    end

    if movie_2.sentiment[:distribution_stats][:st_dev] > movie_1.sentiment[:distribution_stats][:st_dev]
      winners[:review_controversy] = movie_2.title
    elsif movie_2.sentiment[:distribution_stats][:st_dev] < movie_1.sentiment[:distribution_stats][:st_dev]
      winners[:review_controversy] = movie_1.title
    end

    winners
  end
end

app/views/movies/show/_actions.html.slim
=link_to 'Public View', movie_path(movie)
br
=link_to 'Edit', edit_movie_path(movie)
br
=button_to 'Delete', movie, {onclick: "return confirm('Sure?')", method: :delete}
br
=image_tag(movie.image_url)
br
table
  tbody
    tr
      th Rotten Tomatoes ID
      td =movie.rotten_tomatoes_id
    tr
      th Slug
      td =movie.slug
    tr
      th Scan Depth
      td ="#{movie.page_depth} pages"
    tr
      th Year
      td =movie.year
    tr
      th Genres
      td =movie.genres.join(', ')

app/views/movies/show/_build_summary.html.slim
-unless movie.status
  =link_to 'Build Summary', build_movie_path(movie)
-else
  div id=('build-progress')
    .progress
      span.meter id=("#{movie.id}") style=("width: #{movie.status}")
  =link_to 'Restart', build_movie_path(movie)
-if movie.complete?
  table
    -movie.sentiment[:topics].each do |k,v|
      tr
        td =k
        td =v.round(3)
  =render "topics_graph", id: movie.id, topics: movie.sentiment[:topics]

  table
    -movie.sentiment[:people].each do |k, v|
      tr
        td =k
        td =(v * 100).floor

app/views/movies/show/_cast_list.html.slim
table
  tbody
    -cast.each do |member|
      tr
        th =member[:name]
        td =member[:characters].join(',')